AREA: app.main Namespace Reference
app.main Namespace Reference
Functions
lifespan (FastAPI app)
oauth_list_providers (str flow="web")
oauth_public_config (str provider, str flow)
oauth_get_authorization_url (str provider, str flow, str state="")
auth_get_authorization_url_alias (str provider, str flow, str state="")
oauth_callback (str provider, Optional[str] code=None, Optional[str] token=None, str state="", str flow="web", Session session=Depends(lambda:Session(engine)))
oauth_reload ()
str get_client_ip (Request request)
health ()
about (Request request, SessionDep session)
Variables
list origins
list tags_metadata
app = FastAPI(lifespan=lifespan, openapi_tags=tags_metadata)
router_login = APIRouter()
router_user = APIRouter(dependencies=[Depends(oauth2_scheme)])
templates = Jinja2Templates(directory="templates")
allow_origins
allow_credentials
allow_methods
allow_headers
Function Documentation
about()
app.main.about (Request request, SessionDep session)
Definition at line 236 of file main.py.
References app.main.get_client_ip().
auth_get_authorization_url_alias()
app.main.auth_get_authorization_url_alias (str provider, str flow, str state = "")
Definition at line 137 of file main.py.
References app.main.oauth_get_authorization_url().
get_client_ip()
str app.main.get_client_ip (Request request)
Definition at line 221 of file main.py.
Referenced by app.main.about().
health()
app.main.health ()
Definition at line 231 of file main.py.
lifespan()
app.main.lifespan (FastAPI app)
Definition at line 40 of file main.py.
oauth_callback()
app.main.oauth_callback (str provider, Optional[str] code = None, Optional[str] token = None, str state = "", str flow = "web", Session session = Depends(lambda: Session(engine)))
Definition at line 142 of file main.py.
oauth_get_authorization_url()
app.main.oauth_get_authorization_url (str provider, str flow, str state = "")
Definition at line 129 of file main.py.
Referenced by app.main.auth_get_authorization_url_alias().
oauth_list_providers()
app.main.oauth_list_providers (str flow = "web")
Liste tous les providers OAuth2 avec leurs métadonnées.
Retourne : [{id, name, icon, color, available, flows}]
Definition at line 111 of file main.py.
oauth_public_config()
app.main.oauth_public_config (str provider, str flow)
Definition at line 122 of file main.py.
oauth_reload()
app.main.oauth_reload ()
Definition at line 196 of file main.py.
Variable Documentation
allow_credentials
app.main.allow_credentials
Definition at line 216 of file main.py.
allow_headers
app.main.allow_headers
Definition at line 218 of file main.py.
allow_methods
app.main.allow_methods
Definition at line 217 of file main.py.
allow_origins
app.main.allow_origins
Definition at line 215 of file main.py.
app
app.main.app = FastAPI(lifespan=lifespan, openapi_tags=tags_metadata)
Definition at line 104 of file main.py.
origins
list app.main.origins
Initial value:
=  [
    "http://localhost",
    "http://localhost:5173",
    "http://localhost:8080",
    "http://localhost:8081"
]
Definition at line 44 of file main.py.
router_login
app.main.router_login = APIRouter()
Definition at line 106 of file main.py.
router_user
app.main.router_user = APIRouter(dependencies=[Depends(oauth2_scheme)])
Definition at line 107 of file main.py.
tags_metadata
list app.main.tags_metadata
Definition at line 51 of file main.py.
templates
app.main.templates = Jinja2Templates(directory="templates")
Definition at line 200 of file main.py.