AREA: app.token_refresh Namespace Reference
app.token_refresh Namespace Reference
Functions
Dict[str, Any] refresh_oauth_token (str provider_name, str refresh_token, str client_id, Optional[str] client_secret=None, Optional[str] token_url=None)
OAuthConnection refresh_oauth_connection (Session session, OAuthConnection oauth_connection)
ServiceAccount refresh_service_account_token (Session session, ServiceAccount service_account)
bool is_token_expired (Optional[datetime] expires_at, int buffer_minutes=5)
str get_valid_oauth_connection_token (Session session, OAuthConnection oauth_connection)
str get_valid_service_account_token (Session session, ServiceAccount service_account)
Dict[str, Any] batch_refresh_expired_tokens (Session session, int max_count=100)
Function Documentation
batch_refresh_expired_tokens()
Dict[str, Any] app.token_refresh.batch_refresh_expired_tokens (Session session, int max_count = 100)
Definition at line 234 of file token_refresh.py.
get_valid_oauth_connection_token()
str app.token_refresh.get_valid_oauth_connection_token (Session session, OAuthConnection oauth_connection)
Definition at line 212 of file token_refresh.py.
get_valid_service_account_token()
str app.token_refresh.get_valid_service_account_token (Session session, ServiceAccount service_account)
Definition at line 223 of file token_refresh.py.
is_token_expired()
bool app.token_refresh.is_token_expired (Optional[datetime] expires_at, int buffer_minutes = 5)
Definition at line 200 of file token_refresh.py.
refresh_oauth_connection()
OAuthConnection app.token_refresh.refresh_oauth_connection (Session session, OAuthConnection oauth_connection)
Definition at line 69 of file token_refresh.py.
References app.token_refresh.refresh_oauth_token().
refresh_oauth_token()
Dict[str, Any] app.token_refresh.refresh_oauth_token (str provider_name, str refresh_token, str client_id, Optional[str] client_secret = None, Optional[str] token_url = None)
Definition at line 12 of file token_refresh.py.
Referenced by app.token_refresh.refresh_oauth_connection(), and app.token_refresh.refresh_service_account_token().
refresh_service_account_token()
ServiceAccount app.token_refresh.refresh_service_account_token (Session session, ServiceAccount service_account)
Definition at line 130 of file token_refresh.py.
References app.token_refresh.refresh_oauth_token().