AREA: app.db Namespace Reference
app.db Namespace Reference
Functions
get_session ()
scan_yaml_files (base_dir)
load_yaml_file (path)
insert_services (session)
insert_actions_and_reactions (session, service_map)
create_db_tables ()
Variables
POSTGRESQL_URI = str(os.environ.get("POSTGRESQL_URI"))
engine = create_engine(POSTGRESQL_URI)
SessionDep = Annotated[Session, Depends(get_session)]
Function Documentation
create_db_tables()
app.db.create_db_tables ()
Definition at line 159 of file db.py.
References app.db.insert_actions_and_reactions(), and app.db.insert_services().
get_session()
app.db.get_session ()
Definition at line 10 of file db.py.
insert_actions_and_reactions()
app.db.insert_actions_and_reactions (session, service_map)
Definition at line 81 of file db.py.
References app.db.load_yaml_file(), and app.db.scan_yaml_files().
Referenced by app.db.create_db_tables().
insert_services()
app.db.insert_services (session)
Definition at line 33 of file db.py.
References app.db.load_yaml_file(), app.db.scan_yaml_files(), and Service.
Referenced by app.db.create_db_tables().
load_yaml_file()
app.db.load_yaml_file (path)
Definition at line 26 of file db.py.
Referenced by app.db.insert_actions_and_reactions(), and app.db.insert_services().
scan_yaml_files()
app.db.scan_yaml_files (base_dir)
Definition at line 18 of file db.py.
Referenced by app.db.insert_actions_and_reactions(), and app.db.insert_services().
Variable Documentation
engine
app.db.engine = create_engine(POSTGRESQL_URI)
Definition at line 8 of file db.py.
POSTGRESQL_URI
app.db.POSTGRESQL_URI = str(os.environ.get("POSTGRESQL_URI"))
Definition at line 6 of file db.py.
SessionDep
app.db.SessionDep = Annotated[Session, Depends(get_session)]
Definition at line 14 of file db.py.