AREA: app.routers.areas Namespace Reference
app.routers.areas Namespace Reference
Functions
Service require_service (Session session, int service_id)
Action require_action (Session session, int action_id, int service_id)
Reaction require_reaction (Session session, int reaction_id, int service_id)
require_subscription (Session session, int user_id, int service_id)
create_area (AreaCreate area_data, SessionDep session, TokenDep token)
list_areas (SessionDep session, TokenDep token)
Area require_area (SessionDep session, int area_id, int user_id)
toggle_area (int area_id, SessionDep session, TokenDep token)
delete_area (int area_id, SessionDep session, TokenDep token)
Variables
areas_router
TokenDep = Annotated[str, Depends(oauth2_scheme)]
Function Documentation
create_area()
app.routers.areas.create_area (AreaCreate area_data, SessionDep session, TokenDep token)
Definition at line 68 of file areas.py.
References app.routers.areas.require_action(), app.routers.areas.require_reaction(), app.routers.areas.require_service(), and app.routers.areas.require_subscription().
delete_area()
app.routers.areas.delete_area (int area_id, SessionDep session, TokenDep token)
Definition at line 188 of file areas.py.
References app.routers.areas.require_area().
list_areas()
app.routers.areas.list_areas (SessionDep session, TokenDep token)
Definition at line 102 of file areas.py.
require_action()
Action app.routers.areas.require_action (Session session, int action_id, int service_id)
Definition at line 35 of file areas.py.
Referenced by app.routers.areas.create_area().
require_area()
Area app.routers.areas.require_area (SessionDep session, int area_id, int user_id)
Definition at line 168 of file areas.py.
Referenced by app.routers.areas.delete_area(), and app.routers.areas.toggle_area().
require_reaction()
Reaction app.routers.areas.require_reaction (Session session, int reaction_id, int service_id)
Definition at line 42 of file areas.py.
Referenced by app.routers.areas.create_area().
require_service()
Service app.routers.areas.require_service (Session session, int service_id)
Definition at line 29 of file areas.py.
Referenced by app.routers.areas.create_area().
require_subscription()
app.routers.areas.require_subscription (Session session, int user_id, int service_id)
Definition at line 49 of file areas.py.
Referenced by app.routers.areas.create_area().
toggle_area()
app.routers.areas.toggle_area (int area_id, SessionDep session, TokenDep token)
Definition at line 176 of file areas.py.
References app.routers.areas.require_area().
Variable Documentation
areas_router
app.routers.areas.areas_router
Initial value:
=  APIRouter(
    prefix="/areas",
    tags=["areas"],
)
Definition at line 22 of file areas.py.
TokenDep
app.routers.areas.TokenDep = Annotated[str, Depends(oauth2_scheme)]
Definition at line 27 of file areas.py.