AREA: app.routers.services Namespace Reference
app.routers.services Namespace Reference
Functions
get_my_services (SessionDep session, TokenDep token)
SubscriptionRead serialize_subscription (UserServiceSubscription subscription)
get_service_capabilities (int service_id, SessionDep session)
subscribe_service (int service_id, SessionDep session, TokenDep token)
unsubscribe_service (int service_id, SessionDep session, TokenDep token)
Variables
services_router
TokenDep = Annotated[str, Depends(oauth2_scheme)]
Function Documentation
get_my_services()
app.routers.services.get_my_services (SessionDep session, TokenDep token)
Definition at line 35 of file routers/services.py.
References app.routers.services.serialize_subscription().
get_service_capabilities()
app.routers.services.get_service_capabilities (int service_id, SessionDep session)
Definition at line 58 of file routers/services.py.
serialize_subscription()
SubscriptionRead app.routers.services.serialize_subscription (UserServiceSubscription subscription)
Definition at line 48 of file routers/services.py.
Referenced by app.routers.services.get_my_services(), and app.routers.services.subscribe_service().
subscribe_service()
app.routers.services.subscribe_service (int service_id, SessionDep session, TokenDep token)
Definition at line 105 of file routers/services.py.
References app.routers.services.serialize_subscription().
unsubscribe_service()
app.routers.services.unsubscribe_service (int service_id, SessionDep session, TokenDep token)
Definition at line 129 of file routers/services.py.
Variable Documentation
services_router
app.routers.services.services_router
Initial value:
=  APIRouter(
    prefix="/services",
    tags=["services"],
)
Definition at line 21 of file routers/services.py.
TokenDep
app.routers.services.TokenDep = Annotated[str, Depends(oauth2_scheme)]
Definition at line 26 of file routers/services.py.