AREA: app.core.oauth_config Namespace Reference
app.core.oauth_config Namespace Reference
Classes
class MobileOAuthConfig
class ProviderConfig
class WebOAuthConfig
Functions
str _expand_env_vars (str value)
Dict[str, ProviderConfig] _load_providers_file (str path)
Dict[str, ProviderConfig] providers_registry ()
dict public_provider_info (str provider, FlowType flow)
str get_auth_url (str provider, FlowType flow, str state="")
List[dict] list_providers_for_frontend (FlowType flow="web")
None reload_providers ()
Variables
FlowType = Literal["web", "mobile"]
Function Documentation
_expand_env_vars()
str app.core.oauth_config._expand_env_vars (str value) protected
Definition at line 34 of file oauth_config.py.
Referenced by app.core.oauth_config._load_providers_file().
_load_providers_file()
Dict[str, ProviderConfig] app.core.oauth_config._load_providers_file (str path) protected
Definition at line 45 of file oauth_config.py.
References app.core.oauth_config._expand_env_vars().
Referenced by app.core.oauth_config.providers_registry().
get_auth_url()
str app.core.oauth_config.get_auth_url (str provider, FlowType flow, str state = "")
Definition at line 121 of file oauth_config.py.
list_providers_for_frontend()
List[dict] app.core.oauth_config.list_providers_for_frontend (FlowType flow = "web")
Definition at line 182 of file oauth_config.py.
providers_registry()
Dict[str, ProviderConfig] app.core.oauth_config.providers_registry ()
Definition at line 90 of file oauth_config.py.
References app.core.oauth_config._load_providers_file().
public_provider_info()
dict app.core.oauth_config.public_provider_info (str provider, FlowType flow)
Definition at line 96 of file oauth_config.py.
reload_providers()
None app.core.oauth_config.reload_providers ()
Definition at line 205 of file oauth_config.py.
Variable Documentation
FlowType
app.core.oauth_config.FlowType = Literal["web", "mobile"]
Definition at line 6 of file oauth_config.py.